version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    networks:
      - app-network

  consumer:
    build:
      context: ./1_consumer
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - app-network

  app:
    build:
      context: ./2_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
